# Generated by Django 2.1.7 on 2019-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('식사', '식사'), ('문화', '문화'), ('스포츠', '스포츠/레저'), ('취미', '취미/힐링'), ('스터디', '스터디'), ('기타', '기타')], max_length=1),
        ),
    ]
