# Generated by Django 2.1.7 on 2019-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20190521_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='meeting',
            field=models.ForeignKey(on_delete=True, related_name='scrapped', to='meeting.Meeting'),
        ),
    ]
